### ISSUE TITLE
Possible to break the code into branches per video?

### ISSUE THREAD

**Issue by spences10** [notrab/graphql-server-tutorial#1]
Hey @notrab, I thought I'd try get the example in your video up and running and 13 minutes in was the first time you run the server and my code [from following along] failed.

I thought I'd compare what I had against your repo then found something which doesn't represent what was done in the first video.

It's probably too late to do it now for this example but maybe something to bear in mind for future videos?

Maybe if you have the server running first off with maybe `nodemon` then all the changes made after that you can see straight away if there are any issues.

It's late now and the mrs wants to watch Love Island so I'll try this again in the morning

Thanks for the content buddy 👍

**Comment by notrab** [comment]
Hey @spences10 

You're right - It's certainly a long time before I start the server.

I probably spent far too long explaining what we were doing and writing the code when I instead should of got the server running with Nodemon.
